apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx-port
      - name: tomcat-container
        image: tomcat:latest
        ports:
        - containerPort: 8080
          name: tomcat-port
      - name: ubuntu-container
        image: ubuntu:latest
        command: ["/bin/sleep", "infinity"]  # Keeps the container running
