apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: nginx:latest
    command: ["/bin/sh", "-c", "echo Container 1 is running! && sleep 3600"]
    ports:
    - containerPort: 80
  - name: container-2
    image: busybox:latest
    command: ["/bin/sh", "-c", "echo Container 2 is running! && sleep 3600"]
    ports:
    - containerPort: 8080

