apiVersion: v1
kind: Pod
metadata:
  name: env-vars-in-pod
spec:
  containers:
  - name: container-1
    image: nginx:latest
    command: ["/bin/sh", "-c", "echo Container 1 is running! && sleep 3600"]
    ports:
    - containerPort: 80
    env:
    - name: CONTAINER_1_VARIABLE
      value: "ValueForContainer1"
  - name: container-2
    image: busybox:latest
    command: ["/bin/sh", "-c", "echo Container 2 is running! && sleep 3600"]
    ports:
    - containerPort: 8080
    env:
    - name: CONTAINER_2_VARIABLE
      value: "ValueForContainer2"

