apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: app-namespace
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    limits.cpu: "2"
    requests.memory: "500Mi"
    limits.memory: "1Gi"
