apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: app-namespace
spec:
  limits:
  - type: Pod
    max:
      cpu: "1"
      memory: 512Mi
    min:
      cpu: "0.1"
      memory: 64Mi
  - type: Container
    max:
      cpu: "0.5"
      memory: 256Mi
    min:
      cpu: "0.05"
      memory: 32Mi
